on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.31.1'
    - run: hugo
